greenery:

  outputs:
    dbt_zkan:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: "{{ env_var('DBT_ENV_SECRET_PG_PASSWORD') }}"
      dbname: greenery
      schema: dbt_zkan

    prod:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: "{{ env_var('DBT_ENV_SECRET_PG_PASSWORD') }}"
      dbname: greenery
      schema: prod

    dbt_sopap_bigquery:
      type: bigquery
      method: service-account
      project: effective-sonar-384416
      dataset: dbt_sopap
      threads: 1
      keyfile: /workspaces/data-engineering-bootcamp/00-bootcamp-project/effective-sonar-384416-9d9b0d1f4d72.json
      location: asia-southeast1

    prod_bigquery: # poetry run dbt run -t prod_bigquery
      type: bigquery
      method: service-account
      project: effective-sonar-384416
      dataset: deb_bootcamp_prod
      threads: 1
      keyfile: /workspaces/data-engineering-bootcamp/00-bootcamp-project/effective-sonar-384416-9d9b0d1f4d72.json
      location: asia-southeast1

  target: dbt_sopap_bigquery